/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    DepartmentBudgetCard: typeof import('./src/components/DepartmentBudgetCard.vue')['default']
    EmployeeField: typeof import('./src/components/EmployeeField.vue')['default']
    FormSection: typeof import('./src/components/FormSection.vue')['default']
    LeaveRequestDialog: typeof import('./src/components/LeaveRequestDialog.vue')['default']
    LinkControl: typeof import('./src/components/LinkControl.vue')['default']
    PermissionNotice: typeof import('./src/components/PermissionNotice.vue')['default']
    ProcurementLines: typeof import('./src/components/ProcurementLines.vue')['default']
    ProcurementRequestDialog: typeof import('./src/components/ProcurementRequestDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
