/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppGlobalSearch: typeof import('./src/components/AppGlobalSearch.vue')['default']
    AppNotifications: typeof import('./src/components/AppNotifications.vue')['default']
    AppPageHeader: typeof import('./src/components/AppPageHeader.vue')['default']
    AppSearchDialog: typeof import('./src/components/AppSearchDialog.vue')['default']
    AppSidebar: typeof import('./src/components/AppSidebar.vue')['default']
    AppSidebarPanel: typeof import('./src/components/AppSidebarPanel.vue')['default']
    AppSidebarRow: typeof import('./src/components/AppSidebarRow.vue')['default']
    AppTodoList: typeof import('./src/components/AppTodoList.vue')['default']
    BikramDatePicker: typeof import('./src/components/BikramDatePicker.vue')['default']
    ChangeDiff: typeof import('./src/components/ChangeDiff.vue')['default']
    ChangeRequestList: typeof import('./src/components/ChangeRequestList.vue')['default']
    DepartmentBudgetCard: typeof import('./src/components/DepartmentBudgetCard.vue')['default']
    EmployeeRequired: typeof import('./src/components/EmployeeRequired.vue')['default']
    ExpenseClaimDialog: typeof import('./src/components/ExpenseClaimDialog.vue')['default']
    ExpenseClaimLines: typeof import('./src/components/ExpenseClaimLines.vue')['default']
    LeaveRequestDialog: typeof import('./src/components/LeaveRequestDialog.vue')['default']
    LinkControl: typeof import('./src/components/LinkControl.vue')['default']
    PermissionNotice: typeof import('./src/components/PermissionNotice.vue')['default']
    ProcurementLines: typeof import('./src/components/ProcurementLines.vue')['default']
    ProcurementRequestDialog: typeof import('./src/components/ProcurementRequestDialog.vue')['default']
    ProfileSection: typeof import('./src/components/ProfileSection.vue')['default']
    ProposeFieldDialog: typeof import('./src/components/ProposeFieldDialog.vue')['default']
    ProposeRecordDialog: typeof import('./src/components/ProposeRecordDialog.vue')['default']
    RecordFieldControl: typeof import('./src/components/RecordFieldControl.vue')['default']
    RequestGate: typeof import('./src/components/RequestGate.vue')['default']
    RequestTabs: typeof import('./src/components/RequestTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
